#pragma once

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#define PERMISSIVE_HOLD

#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR
#define RGB_MATRIX_DEFAULT_VAL 0

#define SPLIT_TRANSACTION_IDS_USER RPC_ID_SYNC_CAPS_WORD
